# H2 (file-based so data persists)
spring.datasource.url=jdbc:h2:file:./securefiles_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Storage + Crypto
app.crypto.masterKeyBase64=6YZRgtIyxvP32l6Fwmvq3gCbvTpQh+3vS3TcdbvSl10=
app.storage.base-dir=storage
app.storage.nodes=node1,node2,node3
app.storage.replication-factor=2
app.files.maxSizeBytes=52428800

# JWT
app.jwt.secretBase64=xAZIP+/HV3HuhNuGXOnU/CFKx0WW5euOCwmn95MIFbo=
app.jwt.expMinutes=60

# Gmail SMTP (use your Gmail + APP PASSWORD)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Thomafreddy110@gmail.com
spring.mail.password=ezmlwjpwiscyotll
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Where verification links point to
app.frontend.baseUrl=http://localhost:8080