-- =========================
-- USERS
-- =========================
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL,
                       email VARCHAR(100) NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       enabled BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE users ADD CONSTRAINT uk_users_username UNIQUE (username);
ALTER TABLE users ADD CONSTRAINT uk_users_email UNIQUE (email);

CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);

-- =========================
-- VERIFICATION TOKENS
-- =========================
CREATE TABLE verification_tokens (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     token VARCHAR(64) NOT NULL,
                                     user_id BIGINT NOT NULL,
                                     expires_at TIMESTAMP NOT NULL
);

ALTER TABLE verification_tokens
    ADD CONSTRAINT uk_verification_token UNIQUE (token);

ALTER TABLE verification_tokens
    ADD CONSTRAINT fk_verification_user
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE;

CREATE INDEX idx_verification_user_id ON verification_tokens(user_id);

-- =========================
-- FILES  (matches FileRecord.java exactly)
-- =========================
CREATE TABLE files (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       owner_id BIGINT NOT NULL,
                       original_filename VARCHAR(255) NOT NULL,
                       sha256 VARCHAR(64) NOT NULL,
                       size_bytes BIGINT NOT NULL,
                       stored_filename VARCHAR(255) NOT NULL,
                       iv_base64 VARCHAR(24) NOT NULL,
                       encrypted BOOLEAN NOT NULL DEFAULT TRUE,
                       uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE files
    ADD CONSTRAINT fk_files_owner
        FOREIGN KEY (owner_id)
            REFERENCES users(id)
            ON DELETE CASCADE;

-- Prevent same user uploading same file twice
ALTER TABLE files
    ADD CONSTRAINT uk_files_owner_sha UNIQUE (owner_id, sha256);

CREATE INDEX idx_files_owner_id ON files(owner_id);
CREATE INDEX idx_files_sha256 ON files(sha256);

-- =========================
-- SHARE REQUESTS
-- (If your ShareRequest entity differs, paste it and I’ll match exactly.)
-- =========================
CREATE TABLE share_requests (
                                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                file_id BIGINT NOT NULL,
                                from_user_id BIGINT NOT NULL,
                                to_user_id BIGINT NOT NULL,
                                status VARCHAR(20) NOT NULL,
                                created_at TIMESTAMP NOT NULL,
                                responded_at TIMESTAMP,
                                CONSTRAINT fk_share_file FOREIGN KEY (file_id) REFERENCES files(id),
                                CONSTRAINT fk_share_from FOREIGN KEY (from_user_id) REFERENCES users(id),
                                CONSTRAINT fk_share_to FOREIGN KEY (to_user_id) REFERENCES users(id)
);
CREATE INDEX idx_share_file_id ON share_requests(file_id);
CREATE INDEX idx_share_to_user_id ON share_requests(to_user_id);