CREATE TABLE IF NOT EXISTS password_reset_codes (
                                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                    email VARCHAR(255) NOT NULL,
    code VARCHAR(6) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE INDEX IF NOT EXISTS idx_prc_email ON password_reset_codes(email);
CREATE INDEX IF NOT EXISTS idx_prc_code  ON password_reset_codes(code);