ALTER TABLE files ADD COLUMN IF NOT EXISTS content_type VARCHAR(100);

ALTER TABLE files ADD COLUMN IF NOT EXISTS encryption_algorithm VARCHAR(50)
    DEFAULT 'AES/GCM/NoPadding' NOT NULL;

ALTER TABLE files ADD COLUMN IF NOT EXISTS status VARCHAR(20)
    DEFAULT 'STORED' NOT NULL;

ALTER TABLE files ADD COLUMN IF NOT EXISTS download_count BIGINT
    DEFAULT 0 NOT NULL;

ALTER TABLE files ADD COLUMN IF NOT EXISTS replica_nodes VARCHAR(255)
    DEFAULT 'node1' NOT NULL;

ALTER TABLE files ADD COLUMN IF NOT EXISTS last_accessed_at TIMESTAMP;