CREATE TABLE IF NOT EXISTS activity_logs (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             user_id BIGINT NOT NULL,
                                             action_type VARCHAR(50) NOT NULL,
    filename VARCHAR(255),
    file_id BIGINT,
    message VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_activity_logs_user FOREIGN KEY (user_id) REFERENCES users(id)
    );