CREATE TABLE IF NOT EXISTS file_share_links (
                                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                file_id BIGINT NOT NULL,
                                                token VARCHAR(120) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL,
    max_downloads INT NOT NULL,
    current_downloads INT NOT NULL,
    expires_at TIMESTAMP,
    password_hash VARCHAR(120),
    CONSTRAINT fk_file_share_links_file FOREIGN KEY (file_id) REFERENCES files(id)
    );